/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "alttab.c"
#include "aspectresize.c"
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dwmc.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "swallow.c"
#include "tagallmon.c"
#include "vanitygaps.c"
#include "winview.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

