/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alternativetags.h"
#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "alttab.h"
#include "aspectresize.h"
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "fullscreen.h"
#include "movestack.h"
#include "nametag.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "riodraw.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftview.h"
#include "swallow.h"
#include "tagallmon.h"
#include "tapresize.h"
#include "toggletopbar.h"
#include "vanitygaps.h"
#include "winview.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"

