#!/bin/bash

# funcoes cliclaveis
case $BUTTON in
   # 1) bash ~/.dotfiles/.local/bin/dwm/toggle_wifi.sh ;;
    1)
        myip=$(ip -f inet address | grep inet | grep -v 'lo$' | cut -d ' ' -f 6,13 && curl ifconfig.me && echo ' external ip')
        notify-send "Ips atuais" "$myip" --icon "/usr/share/icons/Numix/64/devices/network-modem.svg"
    ;;
    3) bash ~/.dotfiles/.local/bin/dmenu/dmenu-vpn ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

status=$(cat /sys/class/net/enp4s0/operstate | grep "up" -ic)
status_on="BROADCAST,MULTICAST,UP,LOWER_UP"

if [ $status -eq 1 ]; then
    ip=$(ip addr show enp4s0  | grep 'inet' | awk '{print$2}' | sed 's/\/[0-9]*//' | head -1)
    ethernet="^c#6c71c4^󰈀 ^d^$ip  "
else
    ethernet=""
fi

echo "$ethernet"
