#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# tags
bspc monitor -d I II III IV V VI VII VIII IX X

# Seguindo o mouse
bspc config focus_follows_pointer true

# Bordas
bspc config border_width         3
bspc config window_gap          12

# Layouts
bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc config automatic_scheme spiral
#bspc config initial_polarity first_child
#bspc config removal_adjustment true

# how much of the screen the "master" takes by default
# bspc config split_ratio 0.7

# Colors
bspc config focused_border_color \#005469
bspc config normal_border_color \#003F4F

# Gaps
bspc config top_padding 15
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 15

# Configuracoes janelas
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# startup
xrdb ~/.Xresources
pgrep -x mate-power-manager > /dev/null || mate-power-manager &
pgrep -x xautolock > /dev/null || xautolock -time 15 -locker ~/.local/bin/slock_personalizado -detectsleep &
redshift -P -O 4000 &
picom -b
pgrep -x dunst > /dev/null || dunst &
pgrep -x nm-applet > /dev/null || nm-applet &
copyq &
pgrep -x pasystray > /dev/null || pasystray &
pgrep -x solaar > /dev/null || solaar -w hide &
bash ~/.local/bin/if_monitor.sh
#feh --recursive --bg-fill --randomize ~/.wallpapers/* &
bash ~/.fehbg
$HOME/.config/polybar/launch.sh &
