#!/bin/sh

# funcoes cliclaveis
case $BUTTON in
    4) bash ~/.dotfiles/.local/bin/dwm/brilho_tela_aumenta ;;
    5) bash ~/.dotfiles/.local/bin/dwm/brilho_tela_diminui ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

brilho=$(brightnessctl | awk '/%/ {print$4}' | cut -c 2-4 | sed 's/%//' | sed 's/)//')
brilhoIcone="^c#268bd2^󰃠 ^d^$brilho󰏰"

echo "$brilhoIcone  "
