;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ess-eval-region-or-function-or-paragraph-and-step
	))

(setq mc/cmds-to-run-once
      '(
	electric-newline-and-maybe-indent
	))
